spring.application.name=chat-service
server.port=8084
spring.profiles.active=local
#EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#JWT
jwt.secret=c4d76e6b9d23faa12a8c7f34dbe92012f314876b19f6245dcba88278210df45a
spring.datasource.url=jdbc:postgresql://localhost:5432/micro_services
spring.datasource.username=postgres
spring.datasource.password=sougata